services:
  skateland-west:
    build: .
    restart: unless-stopped
    env_file: .env.production
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    external: true
